### ISSUE TITLE
Distribute Ubuntu MATE Welcome as a snap package

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-welcome-legacy#30]
Originally reported by: **Polihron Alexandru (Bitbucket: [APoliTech](https://bitbucket.org/APoliTech), GitHub: [APoliTech](https://github.com/APoliTech))**

----------------------------------------

Because software boutique is used more and more , will be nice to have a snap package for non mate interfaces!

----------------------------------------
- Bitbucket: https://bitbucket.org/ubuntu-mate/ubuntu-mate-welcome/issue/30

**Comment by apolitech** [comment]
You can close this request because has been released. Thanks
