### ISSUE TITLE
Double errors in version 2016.08.09-yakkety-4a9229b

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-welcome-legacy#45]
Originally reported by: **Polihron Alexandru (Bitbucket: [APoliTech](https://bitbucket.org/APoliTech), GitHub: [APoliTech](https://github.com/APoliTech))**

----------------------------------------

![Screenshot at 2016-08-19 15-09-19.png](https://bitbucket.org/repo/aAjn6M/images/3814457893-Screenshot%20at%202016-08-19%2015-09-19.png)![Screenshot at 2016-08-19 15-09-27.png](https://bitbucket.org/repo/aAjn6M/images/3402621612-Screenshot%20at%202016-08-19%2015-09-27.png)

Lets say that you have a broken package in you system. When you are trying to install a app via software boutique you will get the normal broken package  (you can see it in the first pic)
but after you press  close you will get again the same error (see pic 2)

----------------------------------------
- Bitbucket: https://bitbucket.org/ubuntu-mate/ubuntu-mate-welcome/issue/45

**Comment by apolitech** [comment]
Please mark for close as this problem was fixed. Thanks
