### ISSUE TITLE
Translating strings in ubuntu-mate-welcome.desktop

### ISSUE THREAD

**Issue by scootergrisen** [ubuntu-mate/ubuntu-mate-welcome-legacy#58]
The ubuntu-mate-welcome.desktop file have some strings to translated.
Maybe they should be added to the translations on Transifex?
It seem only "name" have been translated but not "comment" for some reason.

**Comment by nybogard** [comment]
I've added a bug report in Launchpad that also details this issue.
[Mate menu example](https://launchpadlibrarian.net/456092025/VirtualBox_Ubuntu-Mate_17_12_2019_16_06_34.png)

[Link to Launchpad bug](https://bugs.launchpad.net/ubuntu-mate/+bug/1856722)

**Comment by JerareYoshi** [comment]
Also happen with software-boutique

**Comment by lah7** [comment]
Fixed! The strings are now translatable on Transifex and will be updated in the launcher files.
