### ISSUE TITLE
Improving the Sound and Video selections

### ISSUE THREAD

**Issue by danboid** [ubuntu-mate/ubuntu-mate-welcome-legacy#60]
mpv should get added no questions asked because it is the ultimate video player for Linux. No competition, especially when you use my mpv config files to add zoom and pan controls:

https://github.com/danboid/mpv-configs

I would like to see mhwaveedit added because I find its interface greatly preferable to Audacity's clunky, ugly mess of a UI which is overkill for most users anyway. mhwaveedit is all I need for cropping, normalising and maybe sometimes adding some simple fades or FX. When I need more power than what mhwaveedit offers, I use the (non-free but unrestricted) REAPER, which I would also like to see added to welcome.

xcfa (X Convert File Audio) is a much better GUI audio conversion tool than soundconverter, hence I'd like to see that added too.

https://packages.ubuntu.com/search?keywords=xcfa

I would be biased but my fave image viewer is shufti. That would probably make more sense to add to the graphics section rather than Sound and Video:

https://github.com/danboid/shufti

**Comment by flexiondotorg** [comment]
Please do not open multiple issues in one issue. That said, most of this is opinion and the applications you prefer are either not available in the archive or don't integrate with the MATE desktop as well as the existing options we provide.
