### ISSUE TITLE
Not found in Bionic

### ISSUE THREAD

**Issue by thwaller** [ubuntu-mate/ubuntu-mate-welcome-legacy#61]
Is this not available for Bionic? I see for Artful and earlier only. I am asked to install via:
"Ubuntu MATE Welcome is not installed. Open a terminal and execute 'snap install ubuntu-mate-welcome --classic' to install it."

The "ubuntu-mate-welcome" package is installed, v18.10.0.

**Comment by flexiondotorg** [comment]
Yes, `ubuntu-mate-welcome` is distributed as a snap:

    snap install ubuntu-mate-welcome --classic
