### ISSUE TITLE
I constantly get this error "Fetch and check assertions for snap "ubuntu-mate-welcome" (221) (Get https://api.snapcraft.io/api/v1/snaps/assertions/snap-declaration/16/qDxAwZcZ5yynyGcfaFSmKyNwUsqyRdwJ?max-format=2: net/http: request canceled (Client.Timeout exceeded while awaiting headers))" when I tried to install the Ubuntu 18.04 -Welcome

### ISSUE THREAD

**Issue by Acees** [ubuntu-mate/ubuntu-mate-welcome-legacy#65]
I don't know if there exist a similar thread to this one, but I tried all possible solutions pertaining to this error by googling and found codes in this link https://snapcraft.io/ubuntu-mate-welcome given by Martin Wimpress (flexiondotorg) in that I can install Ubuntu Mate Welcome, but when I tried this code

snap install ubuntu-mate-welcome --classic

it gives me this:

error: cannot perform the following tasks:
- Fetch and check assertions for snap "ubuntu-mate-welcome" (221) (Get https://api.snapcraft.io/api/v1/snaps/assertions/snap-declaration/16/qDxAwZcZ5yynyGcfaFSmKyNwUsqyRdwJ?max-format=2: net/http: request canceled (Client.Timeout exceeded while awaiting headers))

but then when I tried to open that link in the error and hope I can find some solutions in there. But I didn't I'm new to the linux world probably have more to learn but I'm asking all the techs out there to please help me with this one.

Also when I tried to install Software-Boutique by this line of code:

sudo snap install software-boutique --classic

I get this error:

error: cannot perform the following tasks:
- Download snap "software-boutique" (28) from channel "stable" (received an unexpected http response code (503) when trying to download https://fastly.cdn.snapcraft.io/download-origin/fastly/YaXXC0F47JHW71NlT31UQ2ZYDZ7Vj9l6_28.snap?token=1541912400_5f49fb551dced384dde69db4d09ec4e5080fd6fa)

Any help would highly be appreciated and thanks in advance guys. More power!

**Comment by flexiondotorg** [comment]
This is not a bug in `ubuntu-mate-welcome` but in `snapd`:

  * https://github.com/snapcore/snapd
  * https://bugs.launchpad.net/snapd
