### ISSUE TITLE
Emby Server not installing

### ISSUE THREAD

**Issue by apolitech** [ubuntu-mate/ubuntu-mate-welcome-legacy#69]
Emby Server not installing in 18.04.x

The following packages have unmet dependencies:

emby-server: Depends: libmono-corlib4.5-cil (>= 4.0.0~alpha1) but 4.8.1.0-0xamarin1 is to be installed
             Depends: libmono-system-configuration4.0-cil (>= 4.0.0~alpha1) but 4.8.1.0-0xamarin1 is to be installed
             Depends: libmono-system-core4.0-cil (>= 4.0.0~alpha1) but 4.8.1.0-0xamarin1 is to be installed
             Depends: libmono-system-runtime-serialization4.0-cil (>= 4.0.0~alpha1) but 4.8.1.0-0xamarin1 is to be installed
             Depends: libmono-system-xml4.0-cil (>= 3.12.0) but 4.8.1.0-0xamarin1 is to be installed
             Depends: libmono-system4.0-cil (>= 4.0.0~alpha1) but 4.8.1.0-0xamarin1 is to be installed
             Depends: mono-devel (>= 4.6) but 4.8.1.0-0xamarin1 is to be installed

**Comment by flexiondotorg** [comment]
Emby has been removed.
