### ISSUE TITLE
Ubuntu MATE Welcome shows white window on VirtualBox with enabled 3D acceleration

### ISSUE THREAD

**Issue by N0rbert** [ubuntu-mate/ubuntu-mate-welcome-legacy#72]
I have VirtualBox 5.1.38 host running Ubuntu MATE 16.04.6 LTS.
Also I have Ubuntu MATE 19.04 guest with installed `virtualbox-guest-x11` package. The 3D acceleration is enabled for this VM.
When I run `ubuntu-mate-welcome` it shows white window instead of normal contents.
The `snap list` shows the following output:

```
$ snap list
Name                 Version           Rev   Tracking  Publisher      Notes
core                 16-2.38           6673  stable    canonical✓     core
software-boutique    0+git.9cc961a     39    stable/…  flexiondotorg  classic
ubuntu-mate-welcome  17.10.28-f853dec  319   stable/…  flexiondotorg  classic
```

Some info about graphics and modules:
```
$ lsmod | grep drm
drm_kms_helper        180224  1 vboxvideo
syscopyarea            16384  1 drm_kms_helper
sysfillrect            16384  1 drm_kms_helper
sysimgblt              16384  1 drm_kms_helper
fb_sys_fops            16384  1 drm_kms_helper
drm                   475136  5 drm_kms_helper,vboxvideo,ttm

$ modinfo vboxvideo | head -n1
filename:       /lib/modules/5.0.0-13-generic/kernel/drivers/staging/vboxvideo/vboxvideo.ko
```

See https://ubuntu-mate.community/t/welcome-screen-and-software-boutique-screens-are-blank/10513/31?u=norbert_x for reference.
Also happens on 18.04 LTS and 18.10 (because of snap nature).
But does not happen if I install *VBoxGuestAdditions_5.1.38.iso*.

**Comment by flexiondotorg** [comment]
This was fixed via https://github.com/ubuntu-mate/ubuntu-mate-welcome-legacy/commit/749ebc741c601c2a33215db8918afc0653d49d09
