### ISSUE TITLE
Add Jellyfin to software welcome list

### ISSUE THREAD

**Issue by joshuaboniface** [ubuntu-mate/ubuntu-mate-welcome-legacy#73]
Hello, Joshua here, one of the leaders of the Jellyfin project! We're a FOSS-focused fork of Emby's 3.5.3 codebase continuing on the philosophy of a free media streaming setup with no "premium" functionality and self-hosted control (no central services, Chromecast app aside).

We see that Emby was removed in #69, and would like to suggest our own inclusion in its place.

Currently we provide a 3rd-party repository with packages for Ubuntu Xenial, Bionic, Cosmic, and Disco at https://repo.jellyfin.org/ubuntu

**Comment by flexiondotorg** [comment]
I'll look into that :smiley:
