### ISSUE TITLE
Raspberry Pi: Welcome suddenly crashes without pressing exit.

### ISSUE THREAD

**Issue by RudraSwat** [ubuntu-mate/ubuntu-mate-welcome-legacy#76]
The Welcome screen on the Raspberry PI 3B (armv8) would suddenly crash. This might cause beginners to get confused and reinstall their system since they might think that they have been attacked by a virus (which in any case, isn't true).

My username of Ubuntu Mate Discourse: rs2009.

**Comment by lah7** [comment]
I don't have a Raspberry Pi 3B to test. When you say crash, does the window just disappear?

If so, please provide the output of:

    ubuntu-mate-welcome -v

Also, is this a newly imaged system or have all the updates been applied?

**Comment by franksmcb** [comment]
I’m closing this issue because it has been inactive for an extended time.

Please reopen if you still encounter this issue with the latest stable version.
