### ISSUE TITLE
displaycal is not available for focal - should be removed

### ISSUE THREAD

**Issue by N0rbert** [ubuntu-mate/ubuntu-mate-welcome-legacy#81]
According to https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=displaycal the `displaycal` is not available for Ubuntu 20.04 LTS - Focal Fossa

Please update `data/js/applications.json` - remove *focal* from https://github.com/ubuntu-mate/ubuntu-mate-welcome-legacy/blob/17e3388ef2f3609981cb370bdbad6c5d6a35f574/data/js/applications.json#L1470 .

**Comment by franksmcb** [comment]
I can confirm this.
