### ISSUE TITLE
Link in Welcome app for Ubuntu MATE's Mastodon account is not working

### ISSUE THREAD

**Issue by saivinoba** [ubuntu-mate/ubuntu-mate-welcome-legacy#88]
In welcome application, currently if we click on mastodon icon, it tries to open link as https://ubuntu.social/@ubuntumate but fails. 

The error in firefox is 'Unable to connect' whereas in chrome it says 'ERR_CONNECTION_REFUSED'. 

From within mastodon account if I search for ubuntumate, I see @ubuntumate@ubuntu.social and I'm able to follow. I shows as 'Bot' though (It is same for @ubuntu account as well).

I have raised a bug on launchpad. https://bugs.launchpad.net/ubuntu-mate/+bug/1916853

**Comment by lah7** [comment]
Thanks for spotting that! Footer links have been updated. The beta snap should reflect this shortly.

From what I understand, Ubuntu's Mastodon has been discontinued.
